# Copyright 2025 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

site_name: CWL to PlantUML
site_url: https://terradue.github.io/cwl2puml/
site_author: Fabrice Brito, Simone Tripodi
repo_url: https://github.com/Terradue/cwl2puml/
repo_name: Terradue/cwl2puml

theme:
    logo: imgs/icon-eoap.png
    name: material

    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - mermaid2:
      version: 11.4.1
  - mkdocs-jupyter:
      execute: true
      show_input: True
      no_input: False

markdown_extensions:
  - pymdownx.details
  - abbr
  - admonition
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - attr_list
  - pymdownx.snippets:
      base_path: './'
  - pymdownx.highlight:
      line_spans: __span

extra_css:
  - styles/css/app.css
  
extra_javascript:
  - javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - index.md
  - API doc: api/latest/cwl2puml/index.md
  - Examples:
    - examples.ipynb
    - patterns.ipynb

copyright: <a href="https://www.apache.org/licenses/LICENSE-2.0"><img src="https://img.shields.io/badge/license-Apache%20License%202.0-blue"" alt="Apache License, Version 2.0" /></a>
